### ISSUE TITLE
semi-colon ";" in data: uri will break the unminified CSS

### ISSUE THREAD

**Issue by karlcow** [mrcoles/cssunminifier#2]
This will be unminified with a break after `data:image/png;` and will make the `background-image unusable.`

``` css
.test {color:#000;background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFgAAAA4AgMAAAAED9f9AAAACVBMVEUAAABmZmZmZmaO3ZBrAAAAA3RSTlMA5rA5MyM4AAAAJElEQVQ4y2MYOUA1FAEiEMKiSMIheIUxDRkFo9Ew2MFoeBMDAPLUMTllKtkfAAAAAElFTkSuQmCC);}
```

**Comment by cmalard** [comment]
If re-minified, it makes all the code after background-image unusable. Just ran into this, quite surprising:
```css
 .ais-search-box--powered-by-link{background-image:url('data:image/svg+xml;utf8,<svg></svg>');vertical-align:middle;}
```
is converted to:
```css
 .ais-search-box--powered-by-link {
    background-image: url('data:image/svg+xml;
    utf8, <svg></svg>');
    vertical-align: middle;
}
```
https://mrcoles.com/blog/css-unminify/
if it is re-minified:
```css
 .ais-search-box--powered-by-link{image:url('data:image/svg+xml;
utf8,<svg></svg>');vertical-align:middle;}
```
