### ISSUE TITLE
Whitespace between property name and colon (:) is not removed

### ISSUE THREAD

**Issue by gerritgriebel** [mrcoles/cssunminifier#3]
IMHO, this

    .hide-for-print {
        display             : none;
    }

should become

    .hide-for-print {
        display: none;
    }

**Comment by OwenMelbz** [comment]
Hi,

We've also got what sounds like a similar issue.

However the code we input is

```css
@media (min-width: 1024px) {.navigation .pink-underline::after {bottom: 4px}}
```

but we get out

```css
@media (min-width: 1024px) {
    .navigation .pink-underline: :after {
    bottom: 4px;
}
```

You can see theres an extra space between `: :after`

Any advice would be appreciated! 

Thanks
